


name = "batikakao"
type = "javascript"  # Javascript로 작성한다고 지정
main = "./index.js"

account_id = "e00cb78622e6e71d6f64a4a99a719bff"  # Cloudflare 계정 ID
workers_dev = true
compatibility_date = "2025-02-17"
